"use client";

import { motion } from "framer-motion";
import useEmblaCarousel from "embla-carousel-react";
import Autoplay from "embla-carousel-autoplay";
import { Heart, MessageCircle, Share2, Music } from "lucide-react";
import { fadeInUp } from "@/lib/animations";

const products = [
  { name: "Hydra Serum", price: "$45", color: "from-rose-900 to-rose-700" },
  { name: "Cloud Runner", price: "$129", color: "from-zinc-800 to-zinc-600" },
  { name: "Vital Blend", price: "$39", color: "from-green-900 to-green-700" },
  { name: "Luna Ring", price: "$89", color: "from-stone-800 to-stone-600" },
  {
    name: "AirPods Case",
    price: "$29",
    color: "from-gray-900 to-gray-700",
  },
  { name: "Silk Dress", price: "$199", color: "from-amber-900 to-amber-700" },
];

function PhoneFrame({ product }: { product: (typeof products)[number] }) {
  return (
    <div className="flex-[0_0_220px] md:flex-[0_0_260px] px-2">
      <div className="aspect-[9/16] rounded-[2.5rem] border-[8px] border-gray-800 shadow-2xl overflow-hidden relative bg-black">
        <div
          className={`absolute inset-0 bg-gradient-to-b ${product.color}`}
        />

        {/* Mock content overlay */}
        <div className="relative h-full flex flex-col justify-between p-4">
          {/* Top - CineRads watermark */}
          <div className="flex items-center gap-1.5">
            <div className="size-7 rounded-full bg-white/20 flex items-center justify-center">
              <span className="text-[10px] font-bold text-white">CR</span>
            </div>
            <div>
              <p className="text-[10px] font-semibold text-white">CineRads</p>
              <p className="text-[8px] text-white/60">Sponsored</p>
            </div>
          </div>

          {/* Right side - TikTok-style icons */}
          <div className="absolute right-3 bottom-24 flex flex-col items-center gap-4">
            <div className="flex flex-col items-center gap-1">
              <div className="size-9 rounded-full bg-white/10 flex items-center justify-center">
                <Heart className="size-4 text-white" />
              </div>
              <span className="text-[9px] text-white/80">24.5K</span>
            </div>
            <div className="flex flex-col items-center gap-1">
              <div className="size-9 rounded-full bg-white/10 flex items-center justify-center">
                <MessageCircle className="size-4 text-white" />
              </div>
              <span className="text-[9px] text-white/80">1,203</span>
            </div>
            <div className="flex flex-col items-center gap-1">
              <div className="size-9 rounded-full bg-white/10 flex items-center justify-center">
                <Share2 className="size-4 text-white" />
              </div>
              <span className="text-[9px] text-white/80">Share</span>
            </div>
          </div>

          {/* Bottom - Product info */}
          <div className="space-y-2">
            <div className="flex items-center gap-1.5">
              <Music className="size-3 text-white/60" />
              <div className="h-2 w-24 rounded-full bg-white/10 overflow-hidden">
                <div className="h-full w-1/2 bg-white/30 rounded-full" />
              </div>
            </div>
            <div>
              <p className="text-sm font-semibold text-white">
                {product.name}
              </p>
              <p className="text-xs text-white/70">{product.price}</p>
            </div>
            <div className="w-full rounded-lg bg-white/20 py-2 text-center text-[11px] font-medium text-white backdrop-blur-sm">
              Shop Now
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export function VideoCarousel() {
  const [emblaRef] = useEmblaCarousel(
    {
      loop: true,
      align: "start",
      dragFree: true,
    },
    [
      Autoplay({
        delay: 2500,
        stopOnInteraction: false,
        stopOnMouseEnter: true,
      }),
    ]
  );

  return (
    <section className="py-16 md:py-20 overflow-hidden">
      <div className="max-w-6xl mx-auto px-4 sm:px-6 mb-10">
        <motion.p
          {...fadeInUp}
          whileInView={fadeInUp.animate}
          viewport={{ once: true }}
          className="text-center text-xs uppercase tracking-widest text-muted-foreground mb-3"
        >
          See It In Action
        </motion.p>
      </div>
      <div
        ref={emblaRef}
        className="overflow-hidden cursor-grab active:cursor-grabbing"
      >
        <div className="flex">
          {[...products, ...products].map((product, i) => (
            <PhoneFrame key={i} product={product} />
          ))}
        </div>
      </div>
      <motion.p
        {...fadeInUp}
        whileInView={fadeInUp.animate}
        viewport={{ once: true }}
        className="text-center text-sm text-muted-foreground mt-10 max-w-6xl mx-auto px-4 sm:px-6"
      >
        Every video generated by AI. Every persona customizable. Every ad ready
        to run.
      </motion.p>
    </section>
  );
}
